language: python
python:
  - "3.6"
  #- "3.7"
  - "3.8"
  - "3.9"

deploy:
  provider: pypi
  username: __token__
  password:
  edge: true
  twine_check: true

install:
  - pip install pytest-cov
  - python setup.py install
'''
script:
  - pytest --cov=./

jobs:
  include:
    - stage: lint
      name: Code quality checks
      install:
        - pip install pre-commit
      script:
        - pre-commit run --all-files
after_success:
  # code coverage :
  - pip install codecov
  - codecov

'''